set(GLM_SEARCH_PATHS ${DEPENDENCIES_PATH} ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})

find_path(GLM_INCLUDE_PATH
    NAMES glm/glm.hpp
    PATHS ${GLM_SEARCH_PATHS}
    PATH_SUFFIXES include)

find_library(GLM_LIBRARIES
    NAMES glm libglm.a
    PATHS ${GLM_SEARCH_PATHS}
    PATH_SUFFIXES lib)


set(GLM_FOUND NOT)
if (GLM_INCLUDE_PATH AND GLM_LIBRARIES)
    set(GLM_FOUND TRUE)
    message("EXTERNAL LIBRARY 'GLM' FOUND")
else ()
    message("ERROR: EXTERNAL LIBRARY 'GLM' NOT FOUND")
endif (GLM_INCLUDE_PATH AND GLM_LIBRARIES)
